server {
    listen 443 ssl;
    server_name yourdomain.com;

    ssl_certificate /etc/letsencrypt/live/unifi.rishie.se/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/unifi.rishie.se/privkey.pem;

    location / {
        proxy_pass https://localhost:8443;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
